import { Footer } from "@/components/footer";
import Header from "@/components/header";
import ProgressIndicator from "@/components/progress-indicator";
import { QueryProvider } from "@/providers/query-client-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="flex flex-col min-h-screen overflow-x-hidden antialiased h-screen w-full">
        <QueryProvider>
          <Header />
          <Suspense fallback={null}>
            <ProgressIndicator />
          </Suspense>
          <main className="flex-1">
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </main>

          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
