name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - staging
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=${{ github.event.repository.name }}  
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/$REPO_NAME:${BRANCH_NAME}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
